In [3]:
import numpy as np

In [4]:
x=np.array([[2,3,4],[5,6,7]])
print(x)
print(x.ndim)
print(x.dtype)
print(x.size)#number of element

[[2 3 4]
 [5 6 7]]
2
int32
6


In [5]:
#print(x.arrange(1,5))
#start stope intervel dtype
y=x.reshape(3,2)
print(y)

[[2 3]
 [4 5]
 [6 7]]


In [6]:
a=np.array([(1,2,3,4),(3,4,5,6)])
print(a[0][3],a[1,3])

4 6


In [7]:
f=np.linspace(1,100,10)
print(f)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [9]:
y=np.arange(1,4)
y=list(y)
print(y)

z=np.linspace(1,100,10)
z=list(z)
print(z)
l1=[z[0],z[1],z[2]]
l2=[z[3],z[4],z[5]]
l3=[z[6],z[7],z[8]]
x={y[0]:l1,y[1]:l2,y[2]:l3}
print(x)

[1, 2, 3]
[1.0, 12.0, 23.0, 34.0, 45.0, 56.0, 67.0, 78.0, 89.0, 100.0]
{1: [1.0, 12.0, 23.0], 2: [34.0, 45.0, 56.0], 3: [67.0, 78.0, 89.0]}


In [14]:
a=np.array([(1,2,3,4),(3,4,5,6)])

print(a.min())
print(a.max())
print(a.sum())
#sum(axis=0)

1
6
28


In [13]:
a=np.linspace(0,1000,100)
y=a.reshape(10,10)
print(y.sum())
print(y.sum()/100)
"""sum=[0,0,0,0,0,0,0,0,0,0]
for i in range(10):    
    sum[i]=(y.sum(axis=i))
print(sum)"""

50000.0
500.0


'sum=[0,0,0,0,0,0,0,0,0,0]\nfor i in range(10):    \n    sum[i]=(y.sum(axis=i))\nprint(sum)'