In [2]:
import pandas as pd 
import numpy as np

from sklearn.neural_network import MLPClassifier
from sklearn.cross_validation import train_test_split



C:\Users\jervis1.0\Anaconda3\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [3]:
d = pd.read_csv('suv.csv')
da = d.dropna()
print(d.head(8))

FileNotFoundError: File b'suv.csv' does not exist

In [6]:
al = MLPClassifier(verbose=True, solver='sgd')

In [25]:
x = d.iloc[:,1:4]
y = d['Species']
print(x)


     SepalLengthCm  SepalWidthCm  PetalLengthCm
0              5.1           3.5            1.4
1              4.9           3.0            1.4
2              4.7           3.2            1.3
3              4.6           3.1            1.5
4              5.0           3.6            1.4
5              5.4           3.9            1.7
6              4.6           3.4            1.4
7              5.0           3.4            1.5
8              4.4           2.9            1.4
9              4.9           3.1            1.5
10             5.4           3.7            1.5
11             4.8           3.4            1.6
12             4.8           3.0            1.4
13             4.3           3.0            1.1
14             5.8           4.0            1.2
15             5.7           4.4            1.5
16             5.4           3.9            1.3
17             5.1           3.5            1.4
18             5.7           3.8            1.7
19             5.1           3.8        

In [37]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,random_state = 0, test_size= 0.2)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
xtrain = sc.fit_transform(xtrain)
xtest = sc.fit_transform(xtest)
al.fit(xtrain,ytrain)


Iteration 1, loss = 1.22234832
Iteration 2, loss = 1.21995502
Iteration 3, loss = 1.21655124
Iteration 4, loss = 1.21225102
Iteration 5, loss = 1.20715623
Iteration 6, loss = 1.20136261
Iteration 7, loss = 1.19496203
Iteration 8, loss = 1.18803536
Iteration 9, loss = 1.18065423
Iteration 10, loss = 1.17287506
Iteration 11, loss = 1.16476455
Iteration 12, loss = 1.15638211
Iteration 13, loss = 1.14777387
Iteration 14, loss = 1.13898462
Iteration 15, loss = 1.13005764
Iteration 16, loss = 1.12102377
Iteration 17, loss = 1.11191716
Iteration 18, loss = 1.10277236
Iteration 19, loss = 1.09360971
Iteration 20, loss = 1.08444600
Iteration 21, loss = 1.07530987
Iteration 22, loss = 1.06621373
Iteration 23, loss = 1.05716626
Iteration 24, loss = 1.04818548
Iteration 25, loss = 1.03927745
Iteration 26, loss = 1.03043761
Iteration 27, loss = 1.02167720
Iteration 28, loss = 1.01300219
Iteration 29, loss = 1.00442746
Iteration 30, loss = 0.99595496
Iteration 31, loss = 0.98759004
Iteration 32, los

C:\Users\jervis1.0\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:563: ConvergenceWarning: Stochastic Optimizer: Maximum iterations reached and the optimization hasn't converged yet.
  % (), ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='sgd', tol=0.0001, validation_fraction=0.1,
       verbose=True, warm_start=False)

In [38]:
yp = al.predict(xtest)
yp.flatten()

array(['Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa'], 
      dtype='<U15')

In [39]:
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(ytest,yp)
print(confusion)

[[11  0  0]
 [ 0  4  9]
 [ 0  1  5]]


In [40]:
from sklearn.metrics import accuracy_score
print("The accuracy in percentage is :>{} % ".format((accuracy_score(ytest, yp))*100))

The accuracy in percentage is :>66.66666666666666 % 
